title: POLS 8810 (Spring 2023)
logo: /assets/img/logo.png
description: Ozlem will be using this website to share any information about lab sessions of POLS 8810 (Spring 2023). You can find information on variety of topics (i.e., software
software issues, supplementing class material, questions about problem sets, and help with general methodology matters). 
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
